version: '3'
services:
  flink-master:
    image: anas/flink-master:1.10.0
    hostname: flink-master
    container_name: flink-master
    ports:
      - "8080:8080"
      - "8081:8081"
  flink-worker:
    image: anas/flink-worker:1.10.0
    hostname: flink-worker
    container_name: flink-worker
    environment: 
      - FLINK_MASTER_PORT_6123_TCP_ADDR=flink-master
    depends_on:
      - flink-master